# Intermediate SQL

Here you can access every table used in the course. To access each table, you will need to specify the `cinema` schema in your queries (e.g., `cinema.reviews` for the `reviews` table.

---
_Note: When using sample databases such as those that contain course data, you have read-only access. You can run queries, but cannot make any changes such as adding, deleting, or modifying the data (e.g., creating tables, views, etc.)._

## Take Notes

Add notes about the concepts you've learned and SQL cells with queries you want to keep.

_Add your notes here_

In [2]:
-- Count the number of records in the people table
SELECT count(*) AS count_records
FROM cinema.people;

   count_records
0           8397

Find in the hidden cell below some exercises to explore the data and practice your skills:

In [3]:
-- Count the number of birthdates in the people table
SELECT count(birthdate) AS count_birthdate
FROM cinema.people;

   count_birthdate
0             6152

## Explore Datasets
Use the `descriptions`, `films`, `people`, `reviews`, and `roles` tables to explore the data and practice your skills!
- Which titles in the `reviews` table have an IMDB score higher than 8.5?
- Select all titles from Germany released after 2010 from the `films` table.
- Calculate a count of all movies by country using the `films` table.

In [4]:
-- Count the records for languages and countries represented in the films table
SELECT count(language) AS count_languages , count(country) AS count_countries
FROM cinema.films ;

   count_languages  count_countries
0             4968             4968

In [5]:
-- Return the unique countries from the films table
Select DISTINCT country 
FROM cinema.films ;

           country
0     Soviet Union
1        Indonesia
2            Italy
3         Cameroon
4   Czech Republic
..             ...
60         Belgium
61          Mexico
62          Poland
63          Taiwan
64        Thailand

[65 rows x 1 columns]

In [6]:
-- Count the distinct countries from the films table
Select count(DISTINCT country ) AS count_distinct_countries
FROM cinema.films ;

   count_distinct_countries
0                        65

In [7]:
-- Debug this code
SELECT certification
FROM cinema.films
LIMIT 5;

  certification
0     Not Rated
1
2     Not Rated
3     Not Rated
4     Not Rated

In [8]:
-- Debug this code
SELECT film_id ,imdb_score, num_votes
FROM cinema.reviews;

      film_id  imdb_score  num_votes
0        3934         7.1     203461
1        3405         6.4     149998
2         478         3.2       8465
3          74         7.6       7071
4        1254         8.0     241030
...       ...         ...        ...
4963     4801         7.0         75
4964     4264         7.0     181472
4965     4356         6.2      29738
4966      430         5.9      29591
4967       29         8.6     387508

[4968 rows x 3 columns]

In [9]:
-- Debug this code
SELECT count(birthdate) AS count_birthdays
FROM cinema.people;

   count_birthdays
0             6152

In [1]:
-- Rewrite this query
SELECT person_id, role
FROM cinema.roles
LIMIT 10;

   person_id      role
0       1630  director
1       4843     actor
2       5050     actor
3       8175     actor
4       3000  director
5       4019     actor
6       5274     actor
7       7449     actor
8       1459     actor
9       3929     actor

In [1]:
-- Select film_id and imdb_score with an imdb_score over 7.0
SELECT film_id, imdb_score
FROM cinema.reviews
WHERE imdb_score > 7;

      film_id  imdb_score
0        3934         7.1
1          74         7.6
2        1254         8.0
3        4841         8.1
4        3252         7.2
...       ...         ...
1531      199         8.0
1532     1814         7.2
1533     4158         8.0
1534     4086         7.1
1535       29         8.6

[1536 rows x 2 columns]

In [2]:
-- Select film_id and facebook_likes for ten records with less than 1000 likes 
SELECT film_id, facebook_likes
FROM cinema.reviews
WHERE facebook_likes < 1000
LIMIT 10;

   film_id  facebook_likes
0     3405               0
1      478             491
2       74             930
3      740               0
4     2869             689
5     1181               0
6     2020               0
7     2312             912
8     1820             872
9      831             975

In [3]:
-- Count the records with at least 100,000 votes
SELECT count(*) As films_over_100K_votes
FROM cinema.reviews
WHERE num_votes >= 100000

   films_over_100k_votes
0                   1211

In [4]:
-- Count the Spanish-language films
SELECT count(language) As count_spanish
FROM cinema.films
WHERE language = 'Spanish';

   count_spanish
0             40

In [5]:
-- Select the title and release_year for all German-language films released before 2000
SELECT title, release_year
FROM cinema.films
WHERE language = 'German' AND release_year < 2000;

                               title  release_year
0                         Metropolis          1927
1                      Pandora's Box          1929
2  The Torture Chamber of Dr. Sadism          1967
3                           Das Boot          1981
4                       Run Lola Run          1998
5                     Aimee & Jaguar          1999

In [6]:
-- Update the query to see all German-language films released after 2000
SELECT title, release_year
FROM cinema.films
WHERE release_year > 2000
	AND language = 'German';

                         title  release_year
0              Good Bye Lenin!          2003
1                     Downfall          2004
2                 Summer Storm          2004
3          The Lives of Others          2006
4   The Baader Meinhof Complex          2008
5                     The Wave          2008
6                        Cargo          2009
7                 Soul Kitchen          2009
8             The White Ribbon          2009
9                            3          2010
10              Animals United          2010
11             Buen Día, Ramón          2013

In [7]:
-- Select all records for German-language films released after 2000 and before 2010
SELECT *
FROM cinema.films
WHERE language = 'German'
    AND release_year > 2000 AND release_year < 2010;

     id                       title  ...       gross    budget
0  1952             Good Bye Lenin!  ...   4063859.0   4800000
1  2130                    Downfall  ...   5501940.0  13500000
2  2224                Summer Storm  ...     95016.0   2700000
3  2709         The Lives of Others  ...  11284657.0   2000000
4  3100  The Baader Meinhof Complex  ...    476270.0  20000000
5  3143                    The Wave  ...         NaN   5000000
6  3220                       Cargo  ...         NaN   4500000
7  3346                Soul Kitchen  ...    274385.0   4000000
8  3412            The White Ribbon  ...   2222647.0  12000000

[9 rows x 9 columns]

In [11]:
-- Find the title and year of films from the 1990 or 1999
SELECT title, release_year
FROM cinema.films
WHERE (release_year = 1990 OR release_year = 1999)
-- Add a filter to see only English or Spanish-language films
      AND (language = 'English' OR language = 'Spanish')
-- Filter films with more than $2,000,000 gross
      AND gross > 2000000;

                             title  release_year
0                    Arachnophobia          1990
1      Back to the Future Part III          1990
2                   Child's Play 2          1990
3               Dances with Wolves          1990
4                  Days of Thunder          1990
..                             ...           ...
163                       Trippin'          1999
164  Universal Soldier: The Return          1999
165                  Varsity Blues          1999
166                 Wild Wild West          1999
167                 Wing Commander          1999

[168 rows x 2 columns]

In [12]:
-- Select the title and release_year for films released between 1990 and 2000
SELECT title, release_year
FROM cinema.films
WHERE release_year BETWEEN 1990 And 2000
-- Narrow down your query to films with budgets > $100 million
    AND budget > 100000000
-- Amend the query to include Spanish or French-language films
	AND (language = 'Spanish' OR language = 'French');

                                     title  release_year
0  Les couloirs du temps: Les visiteurs II          1998
1                                    Tango          1998

In [13]:
-- Select the names that start with B
SELECT name
FROM cinema.people 
WHERE name LIKE 'B%';

               name
0        B.J. Novak
1      Babak Najafi
2       Babar Ahmed
3    Bahare Seddiqi
4          Bai Ling
..              ...
440   Buster Keaton
441   Busy Philipps
442     Buzz Aldrin
443    Byron Howard
444      Byron Mann

[445 rows x 1 columns]

In [14]:
-- Select the names that have r as the second let
SELECT name
FROM cinema.people
WHERE name LIKE '_r%';

                  name
0             Ara Celi
1        Aramis Knight
2    Arben Bajraktaraj
3      Arcelia Ramírez
4           Archie Kao
..                 ...
526        Troy Garity
527        Troy Miller
528         Troy Nixey
529     Ursula Andress
530      Wray Crawford

[531 rows x 1 columns]

In [16]:
-- Select names that don't start with A
SELECT name
FROM cinema.people
WHERE name NOT LIKE 'A%';

                    name
0                50 Cent
1            Álex Angulo
2     Álex de la Iglesia
3          Ángela Molina
4             B.J. Novak
...                  ...
7763         Zohra Segal
7764     Zooey Deschanel
7765       Zoran Lisinac
7766       Zubaida Sahar
7767       Zuhair Haddad

[7768 rows x 1 columns]

In [17]:
-- Find the title and release_year for all films over two hours in length released in 1990 and 2000
SELECT title, release_year
FROM cinema.films
WHERE duration > 120
    AND release_year IN(1990, 2000)

                         title  release_year
0           Dances with Wolves          1990
1                   Die Hard 2          1990
2                        Ghost          1990
3                   Goodfellas          1990
4             Mo' Better Blues          1990
5                 Pretty Woman          1990
6      The Godfather: Part III          1990
7     The Hunt for Red October          1990
8        All the Pretty Horses          2000
9                Almost Famous          2000
10                  Bamboozled          2000
11                   Cast Away          2000
12                    Chocolat          2000
13          Dancer in the Dark          2000
14             Erin Brockovich          2000
15           Finding Forrester          2000
16                        Fiza          2000
17                   Gladiator          2000
18       Gone in Sixty Seconds          2000
19           Keeping the Faith          2000
20           Love & Basketball          2000
21                Men of Honor          2000
22      Mission: Impossible II          2000
23                Pandaemonium          2000
24              Pay It Forward          2000
25                     Pollock          2000
26               Proof of Life          2000
27                      Quills          2000
28              Reindeer Games          2000
29               Space Cowboys          2000
30                 The 6th Day          2000
31               The Contender          2000
32              The Family Man          2000
33          The House of Mirth          2000
34  The Legend of Bagger Vance          2000
35                 The Patriot          2000
36           The Perfect Storm          2000
37               Thirteen Days          2000
38                     Traffic          2000
39              Vertical Limit          2000
40           What Lies Beneath          2000
41             What Women Want          2000

In [18]:
-- Find the title and language of all films in English, Spanish, and French
SELECT title, language
FROM cinema.films
WHERE language IN('English','Spanish','French');

                    title language
0     The Broadway Melody  English
1           Hell's Angels  English
2      A Farewell to Arms  English
3             42nd Street  English
4      She Done Him Wrong  English
...                   ...      ...
4742              Twisted  English
4743          Unforgotten  English
4744                Wings  English
4745           Wolf Creek  English
4746    Wuthering Heights  English

[4747 rows x 2 columns]

In [19]:
-- Find the title, certification, and language all films certified NC-17 or R that are in English, Italian, or Greek
SELECT title, certification, language
FROM cinema.films
WHERE (certification = 'NC-17' OR certification = 'R')
    And language IN('English', 'Italian', 'Greek');

                         title certification language
0                       Psycho             R  English
1         A Fistful of Dollars             R  Italian
2              Rosemary's Baby             R  English
3               The Wild Bunch             R  English
4                     Catch-22             R  English
...                        ...           ...      ...
2001            The Neon Demon             R  English
2002         The Perfect Match             R  English
2003  The Purge: Election Year             R  English
2004                  The Veil             R  English
2005                  Triple 9             R  English

[2006 rows x 3 columns]

In [20]:
-- Count the unique titles
-- Count the unique titles
SELECT count(DISTINCT title) AS nineties_english_films_for_teens
FROM cinema.films
-- Filter to release_years to between 1990 and 1999
WHERE release_year BETWEEN 1990 And 1999
-- Filter to English-language films
	AND language = 'English'
-- Narrow it down to G, PG, and PG-13 certifications
	AND certification IN('G', 'PG', 'PG-13');

   nineties_english_films_for_teens
0                               310

In [1]:
-- List all film titles with missing budgets
SELECT title AS no_budget_info
FROM cinema.films
WHERE budget IS NULL;

              no_budget_info
0              Pandora's Box
1      The Prisoner of Zenda
2              The Blue Bird
3                      Bambi
4                 State Fair
..                       ...
425              Unforgotten
426                    Wings
427               Wolf Creek
428        Wuthering Heights
429  Yu-Gi-Oh! Duel Monsters

[430 rows x 1 columns]

In [2]:
-- Count the number of films we have language data for
SELECT count(*) AS count_language_known
FROM cinema.films
WHERE language IS NOT NULL;

   count_language_known
0                  4968

In [1]:
-- Query the sum of film durations
SELECT sum(duration) AS total_duration
FROM cinema.films;

   total_duration
0          534882

In [2]:
-- Calculate the average duration of all films
SELECT avg(duration) AS average_duration
FROM cinema.films;

   average_duration
0        107.947931

In [3]:
-- Find the latest release_year
SELECT max(release_year) AS latest_year
FROM cinema.films;

   latest_year
0         2016

In [4]:
-- Find the duration of the shortest film
SELECT min(duration) AS shortest_film
FROM cinema.films;

   shortest_film
0              7

In [1]:
-- Calculate the sum of gross from the year 2000 or later
SELECT sum(gross) AS total_gross
FROM cinema.films
WHERE release_year >= 2000;

    total_gross
0  150900926358

In [2]:
-- Calculate the average gross of films that start with A
SELECT avg(gross) AS avg_gross_A
FROM cinema.films
WHERE title LIKE 'A%';

    avg_gross_a
0  4.789324e+07

In [3]:
-- Calculate the lowest gross film in 1994
SELECT min(gross) AS lowest_gross
FROM cinema.films
WHERE release_year = 1994 ;

   lowest_gross
0        125169

In [4]:
-- Calculate the highest gross film released between 2000-2012
SELECT max(gross) AS highest_gross
FROM cinema.films
WHERE release_year BETWEEN 2000 AND 2012 ;

   highest_gross
0      760505847

In [5]:
-- Round the average number of facebook_likes to one decimal place
SELECT round(avg(facebook_likes), 1) AS avg_facebook_likes
FROM cinema.reviews ;

   avg_facebook_likes
0              7802.9

In [6]:
-- Calculate the average budget rounded to the thousands
SELECT round(avg(budget),-3) AS avg_budget_thousands
FROM cinema.films ;

   avg_budget_thousands
0              39903000

In [7]:
-- Calculate the title and duration_hours from films
SELECT  title, (duration / 60.0) AS duration_hours
FROM cinema.films;

                                                 title  duration_hours
0     Intolerance: Love's Struggle Throughout the Ages        2.050000
1                       Over the Hill to the Poorhouse        1.833333
2                                       The Big Parade        2.516667
3                                           Metropolis        2.416667
4                                        Pandora's Box        1.833333
...                                                ...             ...
4963                                       Unforgotten        0.750000
4964                                             Wings        0.500000
4965                                        Wolf Creek             NaN
4966                                 Wuthering Heights        2.366667
4967                           Yu-Gi-Oh! Duel Monsters        0.400000

[4968 rows x 2 columns]

In [8]:
-- Calculate the percentage of people who are no longer alive
SELECT (count(deathdate) * 100.0 / count(*) ) AS percentage_dead
FROM cinema.people ;

   percentage_dead
0         9.372395

In [9]:
-- Find the number of decades in the films table
SELECT (max(release_year) - min(release_year)) / 10.0 AS number_of_decades
FROM cinema.films;

   number_of_decades
0               10.0

In [10]:
-- Round duration_hours to two decimal places
SELECT title, round((duration / 60.0), 2) AS duration_hours
FROM cinema.films;

                                                 title  duration_hours
0     Intolerance: Love's Struggle Throughout the Ages            2.05
1                       Over the Hill to the Poorhouse            1.83
2                                       The Big Parade            2.52
3                                           Metropolis            2.42
4                                        Pandora's Box            1.83
...                                                ...             ...
4963                                       Unforgotten            0.75
4964                                             Wings            0.50
4965                                        Wolf Creek             NaN
4966                                 Wuthering Heights            2.37
4967                           Yu-Gi-Oh! Duel Monsters            0.40

[4968 rows x 2 columns]

In [1]:
-- Select name from people and sort alphabetically
SELECT name
FROM cinema.people
ORDER BY name;

                 name
0             50 Cent
1             Aaliyah
2       Aaron Ashmore
3          Aaron Hann
4          Aaron Hill
...               ...
8392      Zohra Segal
8393  Zooey Deschanel
8394    Zoran Lisinac
8395    Zubaida Sahar
8396    Zuhair Haddad

[8397 rows x 1 columns]

In [2]:
-- Select the title and duration from longest to shortest film
SELECT title, duration
FROM cinema.films
ORDER BY duration DESC;

                                             title  duration
0                                          Destiny       NaN
1                             Should've Been Romeo       NaN
2                           Hum To Mohabbat Karega       NaN
3     Harry Potter and the Deathly Hallows: Part I       NaN
4                                            Barfi       NaN
...                                            ...       ...
4963                              Anger Management      22.0
4964                                   10,000 B.C.      22.0
4965          Wal-Mart: The High Cost of Low Price      20.0
4966                                        Vessel      14.0
4967                                     The Touch       7.0

[4968 rows x 2 columns]

In [3]:
-- Select the release year, duration, and title sorted by release year and duration
SELECT release_year, duration, title
FROM cinema.films
ORDER BY release_year,duration;

      release_year  duration                                             title
0           1916.0     123.0  Intolerance: Love's Struggle Throughout the Ages
1           1920.0     110.0                    Over the Hill to the Poorhouse
2           1925.0     151.0                                    The Big Parade
3           1927.0     145.0                                        Metropolis
4           1929.0     100.0                               The Broadway Melody
...            ...       ...                                               ...
4963           NaN     197.0                                Deadline Gallipoli
4964           NaN     240.0                                              Emma
4965           NaN     286.0                                       The Company
4966           NaN     334.0                                            Carlos
4967           NaN       NaN                                        Wolf Creek

[4968 rows x 3 columns]

In [4]:
-- Select the certification, release year, and title sorted by certification and release year
SELECT certification, release_year, title
FROM cinema.films
ORDER BY certification, release_year DESC;

     certification  release_year                           title
0                            NaN                       BrainDead
1                            NaN                     Unforgotten
2                            NaN                    The Bachelor
3                            NaN                      The Border
4                            NaN                A Touch of Frost
...            ...           ...                             ...
4963             X        1981.0                      The Beyond
4964             X        1980.0                 Dressed to Kill
4965             X        1970.0  Beyond the Valley of the Dolls
4966             X        1969.0                 Midnight Cowboy
4967             X        1969.0                The Stewardesses

[4968 rows x 3 columns]

In [5]:
-- Find the release_year and film_count of each year
SELECT release_year, count(title) AS film_count
FROM cinema.films
GROUP BY release_year;

    release_year  film_count
0         1954.0           5
1         1988.0          31
2         1959.0           3
3         1964.0          10
4         1969.0          10
..           ...         ...
87        1950.0           1
88        1957.0           2
89        1955.0           2
90        1937.0           2
91        2012.0         220

[92 rows x 2 columns]

In [6]:
-- Find the release_year and average duration of films for each year
SELECT release_year, avg(duration) AS avg_duration
FROM cinema.films
GROUP BY release_year;

    release_year  avg_duration
0         1954.0    140.600000
1         1988.0    107.000000
2         1959.0    136.666667
3         1964.0    119.400000
4         1969.0    126.000000
..           ...           ...
87        1950.0    107.000000
88        1957.0    128.500000
89        1955.0    112.500000
90        1937.0     92.000000
91        2012.0    106.000000

[92 rows x 2 columns]

In [7]:
-- Find the release_year, country, and max_budget, then group and order by release_year and country
SELECT release_year, country, max(budget) AS max_budget
FROM cinema.films
GROUP BY release_year, country
ORDER BY release_year, country

     release_year  country  max_budget
0          1916.0      USA    385907.0
1          1920.0      USA    100000.0
2          1925.0      USA    245000.0
3          1927.0  Germany   6000000.0
4          1929.0  Germany         NaN
..            ...      ...         ...
500           NaN    Japan         NaN
501           NaN   Poland         NaN
502           NaN   Sweden         NaN
503           NaN       UK         NaN
504           NaN      USA   5000000.0

[505 rows x 3 columns]

In [10]:
-- Answering business questions
-- In the real world, every SQL query starts with a business question. Then it is up to you to decide how to write the query that answers the question. Let's try this out.
-- "Most language diversity" can be interpreted as COUNT(DISTINCT ___). Now over to you.

SELECT release_year, count(DISTINCT language) AS count_language
FROM cinema.films
GROUP BY release_year
ORDER BY count_language DESC;

-- 2006 Most language diversity

    release_year  count_language
0         2006.0              17
1         2015.0              15
2         2005.0              14
3         2008.0              13
4         2013.0              13
..           ...             ...
87        1962.0               1
88        1963.0               1
89        1956.0               1
90        1937.0               1
91        1936.0               1

[92 rows x 2 columns]

In [1]:
-- Select the country and distinct count of certification as certification_count
SELECT country, count(DISTINCT certification) AS certification_count
FROM cinema.films
-- Group by country
GROUP BY country
-- Filter results to countries with more than 10 different certifications
HAVING count(DISTINCT certification) > 10;

  country  certification_count
0      UK                   11
1     USA                   13

In [2]:
-- Select the country and average_budget from films
SELECT country, round(avg(budget), 2) AS average_budget
FROM cinema.films
-- Group by country
GROUP BY country
-- Filter to countries with an average_budget of more than one billion
HAVING round(avg(budget), 2) > 1000000000
-- Order by descending order of the aggregated budget
ORDER BY average_budget DESC;

       country  average_budget
0  South Korea    1.383960e+09
1      Hungary    1.260000e+09

In [3]:
-- Select the release_year for films released after 1990 grouped by year
SELECT release_year
FROM cinema.films
WHERE release_year > 1990
GROUP BY release_year;

    release_year
0           2008
1           1991
2           2009
3           2005
4           2013
5           2003
6           2015
7           1993
8           2002
9           2004
10          1997
11          2016
12          1995
13          1992
14          1994
15          2014
16          2010
17          1996
18          2000
19          2011
20          1998
21          2007
22          2006
23          2001
24          1999
25          2012

In [4]:
-- you'll write a query that returns the average budget and gross earnings for films each year after 1990 if the average budget is greater than 60 million.
SELECT release_year, AVG(budget) AS avg_budget, AVG(gross) AS avg_gross
FROM cinema.films
WHERE release_year > 1990
GROUP BY release_year
HAVING AVG(budget) > 60000000
-- Order the results from highest to lowest average gross and limit to one
ORDER BY avg_gross DESC
LIMIT 1;

   release_year    avg_budget     avg_gross
0          2005  7.032394e+07  4.115914e+07