# Introduction to SQL

Here you can access the `books` table used in the course.

--- 
_Note: When using sample databases such as those that contain course data, you have read-only access. You can run queries, but cannot make any changes such as adding, deleting, or modifying the data (e.g., creating tables, views, etc.)._

## Take Notes

Add notes about the concepts you've learned and SQL cells with queries you want to keep.

_Add your notes here_

In [3]:
-- Select unique authors from the books table
SELECT Distinct author
FROM books ;

                author
0       John Heilemann
1      Sheryl Sandberg
2         Brené Brown
3                   DK
4       Rebecca Skloot
..                 ...
243        Craig Smith
244    Laurel Randolph
245        Sarah Palin
246  Ann Whitford Paul
247      Joanna Gaines

[248 rows x 1 columns]

Find in the hidden cell below some exercises to explore the data and practice your skills:

In [4]:
-- Select unique authors and genre combinations from the books table
SELECT Distinct author, genre
FROM books ;

               author        genre
0      Eben Alexander  Non Fiction
1       Adam Mansbach      Fiction
2         Garth Stein      Fiction
3       Gillian Flynn      Fiction
4      Tucker Carlson  Non Fiction
..                ...          ...
245       James Comey  Non Fiction
246     Jaycee Dugard  Non Fiction
247      Thug Kitchen  Non Fiction
248  William P. Young      Fiction
249    Deborah Diesen      Fiction

[250 rows x 2 columns]

## Explore Datasets
Use the `books` table to explore the data and practice your skills!
- Select only the `title` column.
- Alias the `title` column as `book_title`.
- Select the distinct author names from the `author` column.
- Select all records from the table and limit your results to 10.

In [5]:
-- Alias author so that it becomes unique_author
SELECT DISTINCT author AS unique_author
FROM books;

         unique_author
0       John Heilemann
1      Sheryl Sandberg
2         Brené Brown
3                   DK
4       Rebecca Skloot
..                 ...
243        Craig Smith
244    Laurel Randolph
245        Sarah Palin
246  Ann Whitford Paul
247      Joanna Gaines

[248 rows x 1 columns]

In [6]:
-- Select the first 10 genres from books using PostgreSQL
SELECT genre 
FROM books
LIMIT 10;

         genre
0  Non Fiction
1      Fiction
2  Non Fiction
3      Fiction
4  Non Fiction
5      Fiction
6      Fiction
7      Fiction
8  Non Fiction
9      Fiction