# Joining Data with SQL

Here you can access every table used in the course. To access each table, you will need to specify the `world` schema in your queries (e.g., `world.countries` for the `countries` table, and `world.languages` for the `languages` table).

--- 
_Note: When using sample databases such as those that contain course data, you have read-only access. You can run queries, but cannot make any changes such as adding, deleting, or modifying the data (e.g., creating tables, views, etc.)._

## Take Notes

Add notes about the concepts you've learned and SQL cells with queries you want to keep.

_Add your notes here_

In [1]:
-- First Join
SELECT 
    cities.name AS city,
    countries.name AS country,
    countries.region
FROM world.cities
INNER JOIN world.countries
ON cities.country_code = countries.code;

            city               country          region
0        Abidjan         Cote d'Ivoire  Western Africa
1      Abu Dhabi  United Arab Emirates     Middle East
2          Abuja               Nigeria  Western Africa
3          Accra                 Ghana  Western Africa
4    Addis Ababa              Ethiopia  Eastern Africa
..           ...                   ...             ...
225      Yerevan               Armenia     Middle East
226     Yokohama                 Japan    Eastern Asia
227    Zhengzhou                 China    Eastern Asia
228    Zhongshan                 China    Eastern Asia
229        Zunyi                 China    Eastern Asia

[230 rows x 3 columns]

In [2]:
-- Select fields with aliases
SELECT 
    c.code AS country_code,
    name,
    year,
    inflation_rate
FROM world.countries AS c
-- Join to economies (alias e)
INNER JOIN world.economies AS e
-- Match on code field using table aliases
ON c.code = e.code;

    country_code          name  year  inflation_rate
0            AFG   Afghanistan  2010           2.179
1            AFG   Afghanistan  2015          -1.549
2            AGO        Angola  2010          14.480
3            AGO        Angola  2015          10.287
4            ALB       Albania  2010           3.605
..           ...           ...   ...             ...
363          ZAF  South Africa  2015           4.575
364          ZMB        Zambia  2010           8.500
365          ZMB        Zambia  2015          10.107
366          ZWE      Zimbabwe  2010           3.045
367          ZWE      Zimbabwe  2015          -2.410

[368 rows x 4 columns]

In [3]:
SELECT 
    c.name AS country, 
    l.name AS language, 
    official
FROM world.countries AS c
INNER JOIN world.languages AS l
-- Match using the code column
USING(code)

         country  language  official
0    Afghanistan      Dari      True
1    Afghanistan    Pashto      True
2    Afghanistan    Turkic     False
3    Afghanistan     Other     False
4        Albania  Albanian      True
..           ...       ...       ...
904     Zimbabwe     Sotho      True
905     Zimbabwe     Tonga      True
906     Zimbabwe    Tswana      True
907     Zimbabwe     Venda      True
908     Zimbabwe     Xhosa      True

[909 rows x 3 columns]

In [4]:
--In how many countries is the 'Bhojpuri' language spoken--
-- Select country and language name (aliased)
SELECT 
	c.name AS country, 
	l.name AS language
FROM world.countries AS c
-- Join to languages (aliased)
INNER JOIN world.languages AS l
USING(code)
-- Filter for the Bhojpuri language
WHERE l.name = 'Bhojpuri';

     country  language
0  Mauritius  Bhojpuri
1      Nepal  Bhojpuri

In [6]:
--Your task in this exercise is to join tables to return the country name, year, fertility rate, and unemployment rate in a single result from the countries, populations and economies tables--
SELECT 
    name, 
    e.year, 
    fertility_rate,
    unemployment_rate
FROM world.countries AS c
INNER JOIN world.populations AS p
ON c.code = p.country_code
INNER JOIN world.economies AS e
USING(code) ;

            name  year  fertility_rate  unemployment_rate
0    Afghanistan  2010           4.653                NaN
1    Afghanistan  2010           5.746                NaN
2    Afghanistan  2015           4.653                NaN
3    Afghanistan  2015           5.746                NaN
4         Angola  2010           5.996                NaN
..           ...   ...             ...                ...
731       Zambia  2015           5.687                NaN
732     Zimbabwe  2010           3.856                NaN
733     Zimbabwe  2010           4.048                NaN
734     Zimbabwe  2015           3.856                NaN
735     Zimbabwe  2015           4.048                NaN

[736 rows x 4 columns]

In [7]:
-- Add an additional joining condition such that you are also joining on year--
SELECT 
    name, 
	e.year, 
	fertility_rate, 
	unemployment_rate
FROM world.countries AS c
INNER JOIN world.populations AS p
ON c.code = p.country_code
INNER JOIN world.economies AS e
ON c.code = e.code
	AND e.year = p.year;

             name  year  fertility_rate  unemployment_rate
0     Afghanistan  2010           5.746                NaN
1     Afghanistan  2015           4.653                NaN
2          Angola  2010           6.416                NaN
3          Angola  2015           5.996                NaN
4         Albania  2010           1.663              14.00
..            ...   ...             ...                ...
363  South Africa  2015           2.339              25.35
364        Zambia  2010           5.687                NaN
365        Zambia  2015           5.284                NaN
366      Zimbabwe  2010           4.048                NaN
367      Zimbabwe  2015           3.856                NaN

[368 rows x 4 columns]

In [2]:
SELECT 
    c1.name AS city,
    code,
    c2.name AS country,
    region,
    city_proper_pop
FROM world.cities AS c1
-- Perform an inner join with cities as c1 and countries as c2 on country code
INNER JOIN world.countries AS c2
ON c1.country_code = c2.code
ORDER BY code DESC;

             city code  ...                     region city_proper_pop
0          Harare  ZWE  ...             Eastern Africa         1606000
1          Lusaka  ZMB  ...             Eastern Africa         1742979
2       Cape Town  ZAF  ...            Southern Africa         3740026
3    Johannesburg  ZAF  ...            Southern Africa         4434827
4          Durban  ZAF  ...            Southern Africa         3442361
..            ...  ...  ...                        ...             ...
225  Buenos Aires  ARG  ...              South America         3054300
226     Abu Dhabi  ARE  ...                Middle East         1145000
227         Dubai  ARE  ...                Middle East         2643410
228        Luanda  AGO  ...             Central Africa         2825311
229         Kabul  AFG  ...  Southern and Central Asia         3414100

[230 rows x 5 columns]

In [3]:
SELECT 
	c1.name AS city, 
    code, 
    c2.name AS country,
    region, 
    city_proper_pop
FROM world.cities AS c1
-- Join right table (with alias)
LEFT JOIN world.countries AS c2
ON c1.country_code = c2.code
ORDER BY code DESC;

          city  code  ...                     region city_proper_pop
0     Taichung  None  ...                       None         2752413
1       Tainan  None  ...                       None         1885252
2    Kaohsiung  None  ...                       None         2778918
3    Bucharest  None  ...                       None         1883425
4       Taipei  None  ...                       None         2704974
..         ...   ...  ...                        ...             ...
231    Rosario   ARG  ...              South America         1193605
232  Abu Dhabi   ARE  ...                Middle East         1145000
233      Dubai   ARE  ...                Middle East         2643410
234     Luanda   AGO  ...             Central Africa         2825311
235      Kabul   AFG  ...  Southern and Central Asia         3414100

[236 rows x 5 columns]

In [6]:
-- Select region, and average gdp_percapita as avg_gdp
SELECT region, AVG(gdp_percapita) AS avg_gdp
FROM world.countries AS c
LEFT JOIN world.economies AS e
-- Match on code fields
USING(code)
-- Filter for the year 2010
WHERE year = 2010
-- Group by region
GROUP BY region
-- Order by descending avg_gdp
ORDER BY avg_gdp DESC
-- Return only first 10 records
LIMIT 10;

                      region       avg_gdp
0             Western Europe  58130.961496
1           Nordic Countries  57073.997656
2              North America  47911.509766
3  Australia and New Zealand  44792.384766
4            British Islands  43588.330078
5               Eastern Asia  24962.807617
6            Southern Europe  22926.410911
7                Middle East  18204.641515
8           Baltic Countries  12631.029948
9                  Caribbean  11413.339454

In [12]:
-- Modify this query to use RIGHT JOIN instead of LEFT JOIN
SELECT 
    countries.name AS country, 
    languages.name AS language, 
    percent
FROM world.languages
RIGHT JOIN world.countries
USING(code)
ORDER BY language;

                     country   language  percent
0                   Djibouti       Afar      NaN
1                   Ethiopia       Afar      1.7
2                    Eritrea       Afar      NaN
3                    Namibia  Afrikaans     10.4
4               South Africa  Afrikaans     13.5
..                       ...        ...      ...
911             Fiji Islands       None      NaN
912     Virgin Islands, U.S.       None      NaN
913  Virgin Islands, British       None      NaN
914           Czech Republic       None      NaN
915                Palestine       None      NaN

[916 rows x 3 columns]

In [9]:
SELECT 
    name AS country, 
    code, 
    region, 
    basic_unit
FROM world.countries
-- Join to currencies
FULL JOIN world.currencies
USING (code)
-- Where region is North America or name is null
WHERE region = 'North America' 
	OR name IS NULL
ORDER BY region;

          country code         region              basic_unit
0         Bermuda  BMU  North America        Bermudian dollar
1   United States  USA  North America    United States dollar
2          Canada  CAN  North America         Canadian dollar
3       Greenland  GRL  North America                    None
4            None  TMP           None    United States dollar
5            None  FLK           None  Falkland Islands pound
6            None  HKG           None        Hong Kong dollar
7            None  AIA           None   East Caribbean dollar
8            None  NIU           None      New Zealand dollar
9            None  ROM           None            Romanian leu
10           None  SHN           None      Saint Helena pound
11           None  SGS           None           British pound
12           None  TWN           None       New Taiwan dollar
13           None  WLF           None               CFP franc
14           None  MSR           None   East Caribbean dollar
15           None  IOT           None    United States dollar
16           None  CCK           None       Australian dollar
17           None  COK           None      New Zealand dollar

In [10]:
SELECT 
    name AS country, 
	code, 
	region, 
	basic_unit
FROM world.countries
-- Join to currencies
LEFT JOIN world.currencies
USING (code)
WHERE region = 'North America' 
	OR name IS NULL
ORDER BY region;

         country code         region            basic_unit
0        Bermuda  BMU  North America      Bermudian dollar
1         Canada  CAN  North America       Canadian dollar
2  United States  USA  North America  United States dollar
3      Greenland  GRL  North America                  None

In [11]:
SELECT 
    name AS country, 
	code, 
	region, 
	basic_unit
FROM world.countries
-- Join to currencies
INNER JOIN world.currencies
USING (code)
WHERE region = 'North America' 
	OR name IS NULL
ORDER BY region;

         country code         region            basic_unit
0        Bermuda  BMU  North America      Bermudian dollar
1         Canada  CAN  North America       Canadian dollar
2  United States  USA  North America  United States dollar

In [2]:
SELECT 
	c1.name AS country, 
    region, 
    l.name AS language,
	basic_unit, 
    frac_unit
FROM world.countries as c1 
-- Full join with languages (alias as l)
FULL JOIN world.languages AS l
USING(code)
-- Full join with currencies (alias as c2)
FULL JOIN world.currencies AS c2
USING(code)
WHERE region LIKE 'M%esia';

                            country  ... frac_unit
0                          Kiribati  ...      Cent
1                          Kiribati  ...      Cent
2                  Marshall Islands  ...      Cent
3                  Marshall Islands  ...      Cent
4                             Nauru  ...      Cent
5                             Nauru  ...      Cent
6                             Nauru  ...      Cent
7                     New Caledonia  ...   Centime
8                     New Caledonia  ...   Centime
9                             Palau  ...      Cent
10                            Palau  ...      Cent
11                            Palau  ...      Cent
12                            Palau  ...      Cent
13                            Palau  ...      Cent
14                            Palau  ...      Cent
15                 Papua New Guinea  ...      Toea
16                 Papua New Guinea  ...      Toea
17                 Papua New Guinea  ...      Toea
18                 Papua New Guinea  ...      Toea
19                  Solomon Islands  ...      Cent
20                  Solomon Islands  ...      Cent
21                  Solomon Islands  ...      Cent
22                          Vanuatu  ...
23                          Vanuatu  ...
24                          Vanuatu  ...
25                          Vanuatu  ...
26                          Vanuatu  ...
27  Micronesia, Federated States of  ...      None
28  Micronesia, Federated States of  ...      None
29  Micronesia, Federated States of  ...      None
30  Micronesia, Federated States of  ...      None
31  Micronesia, Federated States of  ...      None
32  Micronesia, Federated States of  ...      None
33  Micronesia, Federated States of  ...      None
34  Micronesia, Federated States of  ...      None
35  Micronesia, Federated States of  ...      None
36                     Fiji Islands  ...      None
37         Northern Mariana Islands  ...      None
38         Northern Mariana Islands  ...      None
39         Northern Mariana Islands  ...      None
40         Northern Mariana Islands  ...      None
41         Northern Mariana Islands  ...      None
42         Northern Mariana Islands  ...      None
43         Northern Mariana Islands  ...      None
44                             Guam  ...      None
45                             Guam  ...      None
46                             Guam  ...      None
47                             Guam  ...      None
48                             Guam  ...      None
49                             Guam  ...      None

[50 rows x 5 columns]

In [1]:
SELECT 
    c.name AS country,
	l.name AS language
-- Inner join countries as c with languages as l on code
FROM world.countries AS c
INNER JOIN world.languages AS l
USING(code)
WHERE c.code IN ('PAK','IND')
	AND l.code in ('PAK','IND');

     country    language
0      India       Hindi
1      India     Bengali
2      India      Telugu
3      India     Marathi
4      India       Tamil
5      India        Urdu
6      India    Gujarati
7      India     Kannada
8      India   Malayalam
9      India       Oriya
10     India     Punjabi
11     India    Assamese
12     India    Maithili
13     India       Other
14  Pakistan     Punjabi
15  Pakistan      Sindhi
16  Pakistan     Saraiki
17  Pakistan      Pashto
18  Pakistan        Urdu
19  Pakistan     Balochi
20  Pakistan      Hindko
21  Pakistan      Brahui
22  Pakistan     English
23  Pakistan  Burushaski
24  Pakistan       Other

In [2]:
SELECT 
    c.name AS country,
	l.name AS language
FROM world.countries AS c        
-- Perform a cross join to languages (alias as l)
CROSS JOIN world.languages AS l
WHERE c.code in ('PAK','IND')
	AND l.code in ('PAK','IND');

     country    language
0      India       Hindi
1   Pakistan       Hindi
2      India     Bengali
3   Pakistan     Bengali
4      India      Telugu
5   Pakistan      Telugu
6      India     Marathi
7   Pakistan     Marathi
8      India       Tamil
9   Pakistan       Tamil
10     India        Urdu
11  Pakistan        Urdu
12     India    Gujarati
13  Pakistan    Gujarati
14     India     Kannada
15  Pakistan     Kannada
16     India   Malayalam
17  Pakistan   Malayalam
18     India       Oriya
19  Pakistan       Oriya
20     India     Punjabi
21  Pakistan     Punjabi
22     India    Assamese
23  Pakistan    Assamese
24     India    Maithili
25  Pakistan    Maithili
26     India       Other
27  Pakistan       Other
28     India     Punjabi
29  Pakistan     Punjabi
30     India      Sindhi
31  Pakistan      Sindhi
32     India     Saraiki
33  Pakistan     Saraiki
34     India      Pashto
35  Pakistan      Pashto
36     India        Urdu
37  Pakistan        Urdu
38     India     Balochi
39  Pakistan     Balochi
40     India      Hindko
41  Pakistan      Hindko
42     India      Brahui
43  Pakistan      Brahui
44     India     English
45  Pakistan     English
46     India  Burushaski
47  Pakistan  Burushaski
48     India       Other
49  Pakistan       Other

In [4]:
SELECT 
	c.name AS country,
    region,
    life_expectancy AS life_exp
FROM world.countries AS c
-- Join to populations (alias as p) using an appropriate join
INNER JOIN world.populations AS p
ON c.code = p.country_code
-- Filter for only results in the year 2010
WHERE year = 2010
-- Sort by life_exp
ORDER BY life_exp
-- Limit to five records
LIMIT 5;

                    country           region   life_exp
0                   Lesotho  Southern Africa  47.483414
1  Central African Republic   Central Africa  47.625317
2              Sierra Leone   Western Africa  48.228950
3                 Swaziland  Southern Africa  48.345757
4                  Zimbabwe   Eastern Africa  49.574657

In [1]:
-- Self Join
SELECT 
	p1.country_code, 
    p1.size AS size2010, 
    p2.size AS size2015
FROM world.populations AS p1
INNER JOIN world.populations AS p2
ON p1.country_code = p2.country_code
WHERE p1.year = 2010
-- Filter such that p1.year is always five years before p2.year
    AND p2.year = 2015;

    country_code  size2010    size2015
0            ABW    101597    103889.0
1            AFG  27962208  32526562.0
2            AGO  21219954  25021974.0
3            ALB   2913021   2889167.0
4            AND     84419     70473.0
..           ...       ...         ...
212          XKX   1775680   1801800.0
213          YEM  23591972  26832216.0
214          ZAF  50979432  55011976.0
215          ZMB  13917439  16211767.0
216          ZWE  13973897  15602751.0

[217 rows x 3 columns]

In [1]:
-- Select all fields from economies2015
SELECT *
FROM world.economies2015  
-- Set operation
UNION
-- Select all fields from economies2019
SELECT *
FROM world.economies2019
ORDER BY code, year;

    code  year         income_group  gross_savings
0    AFG  2015           Low income      21.466000
1    AGO  2015  Upper middle income      -0.425000
2    AGO  2019  Lower middle income      25.524848
3    ALB  2015  Upper middle income      13.840000
4    ALB  2019  Upper middle income      14.499826
..   ...   ...                  ...            ...
336  ZAF  2019  Upper middle income      13.465737
337  ZMB  2015  Lower middle income      39.176998
338  ZMB  2019  Lower middle income      39.714393
339  ZWE  2015           Low income       5.563000
340  ZWE  2019  Lower middle income      11.830197

[341 rows x 4 columns]

In [3]:
-- Query that determines all pairs of code and year from economies and populations, without duplicates
SELECT country_code, year
FROM world.populations
UNION
SELECT code, year
FROM world.economies
ORDER BY country_code, year;

    country_code  year
0            ABW  2010
1            ABW  2015
2            AFG  2010
3            AFG  2015
4            AGO  2010
..           ...   ...
429          ZAF  2015
430          ZMB  2010
431          ZMB  2015
432          ZWE  2010
433          ZWE  2015

[434 rows x 2 columns]

In [4]:
SELECT code, year
FROM world.economies
-- Set theory clause
UNION ALL
SELECT country_code, year
FROM world.populations
ORDER BY code, year;

    code  year
0    ABW  2010
1    ABW  2015
2    AFG  2010
3    AFG  2010
4    AFG  2015
..   ...   ...
809  ZMB  2015
810  ZWE  2010
811  ZWE  2010
812  ZWE  2015
813  ZWE  2015

[814 rows x 2 columns]

In [5]:
-- Return all cities with the same name as a country
SELECT name
FROM world.cities
INTERSECT
SELECT name
FROM world.countries;

        name
0  Singapore

In [6]:
-- Return all cities that do not have the same name as a country
SELECT name
FROM world.cities
EXCEPT
SELECT name
FROM world.countries
ORDER BY name;

            name
0        Abidjan
1      Abu Dhabi
2          Abuja
3          Accra
4    Addis Ababa
..           ...
230      Yerevan
231     Yokohama
232    Zhengzhou
233    Zhongshan
234        Zunyi

[235 rows x 1 columns]

In [1]:
SELECT DISTINCT name
FROM world.languages
-- Add syntax to use bracketed subquery below as a filter
WHERE code IN
    (SELECT code
    FROM world.countries
    WHERE region = 'Middle East')
ORDER BY name;

           name
0        Arabic
1       Aramaic
2      Armenian
3   Azerbaijani
4         Azeri
5       Baluchi
6     Bulgarian
7    Circassian
8       English
9         Farsi
10     Filipino
11       French
12     Georgian
13        Greek
14       Hebrew
15        Hindi
16       Indian
17      Kurdish
18        Other
19      Persian
20     Romanian
21      Russian
22       Syriac
23      Turkish
24      Turkmen
25  unspecified
26         Urdu

In [2]:
SELECT code, name
FROM world.countries
WHERE continent = 'Oceania'
-- Filter for countries not included in the bracketed subquery
  AND code NOT IN 
    (SELECT code
    FROM world.currencies);

  code                             name
0  ASM                   American Samoa
1  FJI                     Fiji Islands
2  GUM                             Guam
3  FSM  Micronesia, Federated States of
4  MNP         Northern Mariana Islands

In [3]:
SELECT *
FROM world.populations
WHERE year = 2015
-- Filter for only those populations where life expectancy is 1.15 times higher than average
  AND life_expectancy > 1.15 *
  (SELECT AVG(life_expectancy)
   FROM world.populations
   WHERE year = 2015);

   pop_id country_code  year  fertility_rate  life_expectancy       size
0      21          AUS  2015           1.833        82.451220   23789752
1     376          CHE  2015           1.540        83.197560    8281430
2     356          ESP  2015           1.320        83.380486   46443992
3     134          FRA  2015           2.010        82.670730   66538392
4     170          HKG  2015           1.195        84.278046    7305700
5     174          ISL  2015           1.930        82.860980     330815
6     190          ITA  2015           1.370        83.490240   60730584
7     194          JPN  2015           1.460        83.843660  126958470
8     340          SGP  2015           1.240        82.595120    5535002
9     374          SWE  2015           1.880        82.551216    9799186

In [4]:
-- Select relevant fields from cities table
SELECT
    country_code,
    name,
    urbanarea_pop
FROM world.cities
-- Filter using a subquery on the countries table
WHERE name IN
    (SELECT capital
    FROM world.countries)
ORDER BY urbanarea_pop DESC;

   country_code       name  urbanarea_pop
0           CHN    Beijing       21516000
1           BGD      Dhaka       14543124
2           JPN      Tokyo       13513734
3           RUS     Moscow       12197596
4           EGY      Cairo       10230350
..          ...        ...            ...
61          SEN      Dakar        1146053
62          ARE  Abu Dhabi        1145000
63          LBY    Tripoli        1126000
64          ARM    Yerevan        1060138
65          TUN      Tunis        1056247

[66 rows x 3 columns]

In [6]:
-- Find top nine countries with the most cities
SELECT
    c1.name AS country,
    COUNT(c2.*) AS cities_num
FROM world.countries AS c1
LEFT JOIN world.cities AS c2
ON c1.code = c2.country_code
GROUP BY country
-- Order by count of cities as cities_num
ORDER BY cities_num DESC , country
-- Limit the results
LIMIT 9;

              country  cities_num
0               China          36
1               India          18
2               Japan          11
3              Brazil          10
4            Pakistan           9
5       United States           9
6           Indonesia           7
7  Russian Federation           7
8         South Korea           7

In [7]:
SELECT 
  countries.name AS country,
-- Subquery that provides the count of cities   
  (SELECT COUNT(cities.name)
   FROM world.cities
   WHERE cities.country_code = countries.code) AS cities_num
FROM world.countries
ORDER BY cities_num DESC, country
LIMIT 9;

              country  cities_num
0               China          36
1               India          18
2               Japan          11
3              Brazil          10
4            Pakistan           9
5       United States           9
6           Indonesia           7
7  Russian Federation           7
8         South Korea           7

In [8]:
-- Select local_name and lang_num from appropriate tables
SELECT countries.local_name, sub.lang_num
FROM world.countries,
  (SELECT code, COUNT(*) AS lang_num
  FROM world.languages
  GROUP BY code) AS sub
-- Where codes match
WHERE countries.code = sub.code
ORDER BY lang_num DESC;

                  local_name  lang_num
0                     Zambia        19
1                YeItyop´iya        16
2                   Zimbabwe        16
3                      Nepal        14
4               Bharat/India        14
..                       ...       ...
193                     Cuba         1
194                 Colombia         1
195                Nederland         1
196  Al-´Arabiya as-Sa´udiya         1
197               San Marino         1

[198 rows x 2 columns]

In [9]:
-- Select relevant fields
SELECT 
  code, 
  inflation_rate, 
  unemployment_rate
FROM world.economies
WHERE year = 2015 
  AND code IN
-- Subquery returning country codes filtered on gov_form
  (SELECT code
  FROM world.countries
  WHERE gov_form LIKE '%Monarchy%' OR gov_form LIKE '%Republic%' )
ORDER BY inflation_rate;

    code  inflation_rate  unemployment_rate
0    LBN          -3.749                NaN
1    ZWE          -2.410                NaN
2    KNA          -2.302                NaN
3    MHL          -2.169                NaN
4    VCT          -1.726                NaN
..   ...             ...                ...
173  YEM          39.403                NaN
174  UKR          48.684              9.143
175  VEN         121.738              7.400
176  ARG             NaN                NaN
177  SYR             NaN                NaN

[178 rows x 3 columns]

In [10]:
-- Select fields from cities
SELECT
    name,
    country_code,
    city_proper_pop,
    metroarea_pop,
    city_proper_pop / metroarea_pop * 100 AS city_perc
FROM world.cities
-- Use subquery to filter city name
WHERE name IN
    (SELECT capital
    FROM world.countries
    WHERE continent LIKE '%Europe' OR continent LIKE '%America')
-- Add filter condition such that metroarea_pop does not have null values
    AND metroarea_pop IS NOT NULL
-- Sort and limit the result
ORDER BY city_perc DESC
LIMIT 10;

         name country_code  city_proper_pop  metroarea_pop  city_perc
0        Lima          PER          8852000       10750000  82.344186
1      Bogota          COL          7878783        9800000  80.395746
2      Moscow          RUS         12197596       16170000  75.433493
3      Vienna          AUT          1863881        2600000  71.687728
4  Montevideo          URY          1305082        1947604  67.009616
5     Caracas          VEN          1943901        2923959  66.481817
6        Rome          ITA          2877215        4353775  66.085523
7    Brasilia          BRA          2556149        3919864  65.210146
8      London          GBR          8673713       13879757  62.491822
9    Budapest          HUN          1759407        2927944  60.090184